[package]
name = "json_to_status"
version = "0.1.0"
authors = ["Jaco Hofmann <hofmann@esa.tu-darmstadt.de>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
log = "0.4.6"
common_failures = "0.1.1"
env_logger = "0.6.1"
clap = "2.33.0"
serde_json = "1.0.39"
serde = {version = "1.0.93", features = ["derive"]}
hex = "0.3.2"
prost = "0.5.0"
bytes = "0.4.12"
regex = "1.3.9"

[build-dependencies]
prost-build = "0.5.0"
